# Generated by Django 4.2.4 on 2023-08-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('IMPAYE', 'Impayé'), ('PAYE', 'Payé')], max_length=20),
        ),
    ]
