# Generated by Django 4.2.4 on 2023-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factures', '0002_alter_facture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('Impayé', 'IMPAYE'), ('Payé', 'PAYE')], max_length=20),
        ),
    ]
