# Generated by Django 4.2.4 on 2023-09-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factures', '0003_alter_facture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('AUTRE', 'Autre'), ('Null', 'null')], default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='position',
            field=models.CharField(choices=[('AVANT', 'avant'), ('ARRIERE', 'arriere'), ('Null', 'null')], default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='produitfacture',
            name='montant',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
